### ISSUE TITLE
Allow users to install and deploy Mathesar in multiple ways

### ISSUE THREAD

**Issue by kgodey** [mathesar-foundation/mathesar#2509]
In preparation for the first release, we need tooling and documentation to help users and admins deploy, install, and manage Mathesar in different contexts. These tasks need to be made as painless as possible.

We've organized this by different deployment types, and the intent is to do lower-numbered deployment types before higher-numbered ones. For all deployment types, they should begin at some kind of "Install Mathesar" page on `docs.mathesar.org` (linked from `mathesar.org`) listing various options.

- [x] https://github.com/centerofci/mathesar/issues/2034
- [x] https://github.com/centerofci/mathesar/issues/2508
- [ ] https://github.com/centerofci/mathesar/issues/2427
- [ ] https://github.com/centerofci/mathesar/issues/2633
- [ ] https://github.com/centerofci/mathesar/issues/2707

**Comment by MarkCupitt** [comment]
How about Kubernetes you can use this tool, to convert the docker compose file to a kubernetes install yaml 

https://github.com/kubernetes/kompose

I gave it a try, seems work except for the HTTP_PORT var which I hard coded

connecting to existing db is critical as well, probably the most important to be honest

**Comment by kgodey** [comment]
Thanks @MarkCupitt. I've added it to the checklist in the main file. We've also had a request for a Helm chart (#2633), which seems related.

cc @silentninja since you're working on installation improvements.

**Comment by kgodey** [comment]
Closing this in favor of new issues:
- #4588 
- #4589 
- #4587 
- #4579
