### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by varshadr** [mathesar-foundation/mathesar#2888]
## Problem
Currently there is no proper API documentation.This project aims at automation of API documentation generation for Mathesar’s current and upcoming APIs in a well-defined standard that can be easily understood by the developers.

## Proposed solution

To achieve it, we will use a library, DRF Spectacular, which can generate Open API specification automatically based on the backend implementation. Open API is a well-defined standard supported by a large community and provides a machine-readable format for describing the functionality of the API. Additionally, Open API documentation can be easily consumed in different formats like JSON or YAML.We will generate it in YAML format,as it is a more human-readable format and would enable developers to use any api platform of their choice(like postman, hopscotch, etc).
Swagger UI is a tool that can be used to visualize and interact with the Open API documentation. It provides a user-friendly interface for exploring the API endpoints, parameters, and responses.We will integrate Swagger UI to DRF Spectacular, to display the API documentation generated by DRF Spectacular.

```[tasklist]
### Tasks
- [ ] #2938
- [ ] #2935
- [ ] https://github.com/centerofci/mathesar/issues/2958
- [ ] #2954
- [ ] #2953
- [ ] #2936
- [ ] https://github.com/centerofci/mathesar/issues/3275
- [ ] https://github.com/centerofci/mathesar/issues/3278
- [ ] Customize the branding of the Swagger UI page to match Mathesar's branding guidelines.
```
