### ISSUE TITLE
Add the generated OpenAPI spec file to the codebase and fix the incorrect specs

### ISSUE THREAD

**Issue by varshadr** [mathesar-foundation/mathesar#2958]
## Problem
This issue aims to add the generated OpenAPI specification file generated by drf-spectacular to the codebase. The OpenAPI spec file provides a comprehensive documentation of the API endpoints, schemas, and operations.

```[tasklist]
### Tasks
- [ ] https://github.com/centerofci/mathesar/issues/2967
- [ ] https://github.com/centerofci/mathesar/issues/2997
- [ ] https://github.com/centerofci/mathesar/issues/3000
- [ ] https://github.com/centerofci/mathesar/issues/3001
- [ ] https://github.com/centerofci/mathesar/issues/3046
- [ ] https://github.com/centerofci/mathesar/issues/3068
- [ ] https://github.com/centerofci/mathesar/issues/3049
- [ ] https://github.com/centerofci/mathesar/issues/3089
- [ ] https://github.com/centerofci/mathesar/issues/3145
- [ ] https://github.com/centerofci/mathesar/issues/3176
- [ ] https://github.com/centerofci/mathesar/issues/3153
- [ ] https://github.com/centerofci/mathesar/issues/3253
- [ ] https://github.com/centerofci/mathesar/issues/3256
- [ ] https://github.com/centerofci/mathesar/issues/3266
- [ ] https://github.com/centerofci/mathesar/issues/3268
- [ ] https://github.com/centerofci/mathesar/issues/3270
- [ ] https://github.com/centerofci/mathesar/issues/3272
```
