### ISSUE TITLE
Move tests to SQL

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3154]
## Problem

Our testing suite consists of _many_ tests that essentially run some operations on the database, then see whether the output is as expected. This is slow and prone to issues when parallelizing, since our current tests do all this from Python.

## Proposed solution

We should move as many tests as possible to SQL tests, using pgTAP. Currently, this is only possible for tests that depend only on functions that are installed on the database as SQL or PL/pgSQL functions.

Python modules whose tests should be moved to SQL are (mostly):

```[tasklist]
### Tasks
- [ ] db.columns.operations.alter
- [x] db.columns.operations.create
- [ ] db.columns.operations.drop
- [x] db.constraints.operations.create
- [x] db.constraints.operations.drop
- [x] db.links.operations.create
- [x] db.schemas.operations.alter
- [x] db.schemas.operations.create
- [x] db.schemas.operations.drop
- [x] db.tables.operations.alter
- [ ] db.tables.operations.create
- [ ] db.tables.operations.drop
```

These should be tackled piecemeal, not all at once.

**Comment by Anish9901** [comment]
SQL tests for `db.tables.operations.create` are already in place, only the mock(s) for the function call are needed for that in the python layer.
