### ISSUE TITLE
Connections work addendum

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3294]
This is to track the (somewhat last-minute) changes in connections functionality that we decided to make before the v0.1.4 release.

```[tasklist]
### Backend work
- [ ] https://github.com/centerofci/mathesar/issues/3291
- [ ] https://github.com/centerofci/mathesar/issues/3292
- [ ] https://github.com/centerofci/mathesar/issues/3293
```

```[tasklist]
### Frontend work
- [ ] https://github.com/centerofci/mathesar/issues/3297
- [ ] https://github.com/centerofci/mathesar/issues/3311
```

**Comment by seancolsen** [comment]
Now that we're down to one remaining sub-issue, I'm closing this meta issue so that the remaining work for v0.1.4 is easier to track.
