### ISSUE TITLE
Architectural overhaul for beta

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3516]
## Problem

The current back end has problems with performance and complexity stemming from keeping and maintaining state about DB-layer objects in the Mathesar web service (specifically in Django models maintained by that service). This meta issue will track the work for that project.

See more **[plans and specs on the wiki](https://wiki.mathesar.org/projects/2024/architecture-transition/)**.

```[tasklist]
### For RC
- [x] Get buy-in and merge [new architecture plan](https://github.com/mathesar-foundation/mathesar-wiki/pull/108)
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3518
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3519
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3531
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3540
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3545
- [ ] https://github.com/mathesar-foundation/mathesar/pull/3543
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3548
- [x] Create working branch for overhaul
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3549
- [x] Draft specs for record summary overhaul
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3625
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3631
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3570
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3575
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3593
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3594
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3592
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3595
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3764
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3675
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3621
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3639
```

```[tasklist]
### For Beta
- [ ] Implement `shared_explorations` RPC methods
- [ ] Implement `shared_tables` RPC methods
```
TODO: Many more tasks.

## Additional context

- [Architecture transition plans](https://wiki.mathesar.org/projects/2024/architecture-transition/)

**Comment by seancolsen** [comment]
Now that we're in the tail end of work for beta, I don't think this issue is useful to have open anymore. We have other issues open to track the remaining work at a more granular level. So I'm closing this.
