### ISSUE TITLE
Get testing for RPC functions organized and set up.

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3518]
```[tasklist]
### Tasks
- [x] Look at https://pypi.org/project/pytest-postgresql/, make sure it works for us
- [x] Set up basic testing framework for RPC endpoint functions
- [x] (blocked) Write initial tests for wiring
```

## Additional context

- [RPC transition plan](https://wiki.mathesar.org/projects/2024/architecture-transition/rpc/)

**Comment by mathemancer** [comment]
Assigning to @Anish9901 to start.
