### ISSUE TITLE
Implement `columns` RPC methods

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3570]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3571
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3583
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3584
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3585
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3640
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3652
```
