### ISSUE TITLE
Implement `tables` RPC methods

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3575]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3613
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3607
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3611
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3600
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3617
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3622
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3634
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3636
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3668
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3645
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3647
```
