### ISSUE TITLE
Implement `records` RPC methods

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3592]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3690
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3707
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3736
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3737
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3738
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3739
```
