### ISSUE TITLE
Implement `schemas` RPC methods

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3593]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3596
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3609
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3619
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3627
```
