### ISSUE TITLE
Implement `explorations` RPC methods

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3595]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3729
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3693
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3726
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3692
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3730
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3724
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3715
```
