### ISSUE TITLE
Implement `data_modeling` RPC methods

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3764]
```[tasklist]
### Tasks
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3765
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3766
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3787
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3788
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3770
- [ ] https://github.com/mathesar-foundation/mathesar/issues/3815
```

**Comment by seancolsen** [comment]
This is done enough that I think it's worth closing now that we're in the final stages of beta work. Remaining work within this issue is already tracked in other issues.
