### ISSUE TITLE
Prefetch SqlAlchemy property objects when querying Django Objects

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#802]
## Problem
Django objects are a thin layer over the reflected database objects, so many fields are just properties that point to an equivalent SqlAlchemy object. The problem is that those underlying objects are generated only when an individual Django object is accessed, resulting in an N+1 query when fetching a list of Django objects.

## Proposed solution
Property fields that do not belong to Django but can be fetched in bulk should be pre-fetched when the Django objects are queried. We could make use of this [library](https://github.com/ionelmc/django-prefetch) to mimic the Django prefetch_related method 

## Additional Context

List of affected objects to be prefetched(Work in progress)|

#### TableSerializer
  - [x] #2883
  - [x] Prefetching Column Name and type
  
#### Column Serializer
 - [x] Prefetching Column Name and type
 
#### Schema Serializer
 - [ ] num_tables field
 - [ ] num_queries field 
 
 #### Constraint Serializer
 - [ ] #1764

**Comment by mathemancer** [comment]
Do you have some examples of where this library would improve things?  Most of the attributes that we loop through (e.g., when listing tables) aren't related to the model via some foreign key relationship.  To solve the problem, we'd need to write a (very complicated) fetcher that could get, e.g., all column details for all columns of each table in the page.  I.e., the column details won't be stored in the (eventual) column model, so they'll need to be queried for each column in real-time anyway.  (Or am I missing something?)

**Comment by silentninja** [comment]
Let's take the `tables/` get api. We fetch all the tables from the django database and the relevant _sa_table is reflected each time the property of the Django table is used(caching reduces this to reflect on first access only). But this could be made better by prefetching when querying for a list of tables using the library.

` _sa_tables = Prefetcher(
            filter = lambda ids: reflect_tables_from_oid(ids),
            reverse_mapper = lambda sa_table: [sa_table.id],
            decorator = lambda table, sa_table=(): setattr(table, '_sa_table', table),
mapper = lambda table: table.oid
        )
`

**Comment by kgodey** [comment]
I think this sounds like a good idea. @silentninja I think you should spec out the specific queries you see us using the library for so that we can evaluate it more thoroughly before implementation.

**Comment by kgodey** [comment]
Closing this since it's not going to be relevant with upcoming architectural changes.
